#!/bin/bash

mesg-cli service:start webhook
mesg-cli service:start email-sendgrid
mesg-cli service:start stripe
mesg-cli service:start ethereum-erc20

if [ "$1" == 'local' ]; then
  ngrok http -subdomain=mesg-stripe-test 3001
fi
